### ISSUE TITLE
Process Timeline 

### ISSUE THREAD

**Issue by Szuchieh** [Szuchieh/szuchieh.github.io#3]
![image](https://cloud.githubusercontent.com/assets/14932463/20649412/837fe796-b4fa-11e6-8eca-32532f9e3b96.png)
Two Changes
1) Make all the circles distribute equally.
2) Make the line start at the first circle, and end at the last circle.

**Comment by mikelduffy** [comment]
The lines before the first element and after the last element have been removed. The spacing is also fixed a bit, but because the staged class is also flex, it is not perfect.
