### ISSUE TITLE
Replace images-Final Prototype

### ISSUE THREAD

**Issue by Szuchieh** [Szuchieh/szuchieh.github.io#6]
Here are the new Hi-Res images for final prototype 
![final prototype 1](https://cloud.githubusercontent.com/assets/14932463/20656357/cb52f560-b566-11e6-961b-5529e2f6be96.png)
![final prototype 2](https://cloud.githubusercontent.com/assets/14932463/20656358/cb53cdf0-b566-11e6-9773-ac953b11d4c7.png)
![final prototype 3](https://cloud.githubusercontent.com/assets/14932463/20656359/cb547232-b566-11e6-98a2-5699c95cc2bb.png)
![final prototype 4](https://cloud.githubusercontent.com/assets/14932463/20656360/cb55c7ea-b566-11e6-8808-8911bcd04653.png)
![final prototype 5](https://cloud.githubusercontent.com/assets/14932463/20656361/cb587ff8-b566-11e6-9a82-7ca16b5f6069.png)

**Comment by mikelduffy** [comment]
Missing two of the images

**Comment by Szuchieh** [comment]
Please upload all of the images on Final Prototype section
